{
 "title": "Zookeeper Exporter",
 "description": "Dashboard for https://github.com/dabealu/zookeeper-exporter\r\n",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "version",
    "query": "label_values(zk_version{instance=~\"$instance\"}, version)"
   },
   { "name": "namespace", "query": "label_values(zk_up, namespace)" },
   {
    "name": "instance",
    "label": "Source of metrics",
    "query": "label_values(zk_up{namespace=\"$namespace\"},instance)"
   },
   {
    "name": "name",
    "label": "Node name",
    "query": "label_values(zk_up{namespace=\"$namespace\", instance=\"$instance\"},zk_host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "zk_up{instance=~\"$instance\", zk_host=~\"$name\"}",
     "legendFormat": "{{zk_host}}"
    }
   ]
  },
  {
   "title": "The Leader Is",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "zk_server_leader{instance=~\"$instance\"}==1"
    }
   ]
  },
  {
   "title": "Watch Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "first",
   "targets": [
    {
     "expr": "zk_watch_count{instance=~\"$instance\", zk_host=~\"$name\"}"
    }
   ]
  },
  {
   "title": "Znode Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "zk_znode_count{instance=~\"$instance\", zk_host=~\"$name\"}"
    }
   ]
  },
  {
   "title": "Ephemerals Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 0 },
   "format": "short",
   "valueName": "first",
   "targets": [
    {
     "expr": "zk_ephemerals_count{instance=~\"$instance\",zk_host=~\"$name\"}"
    }
   ]
  },
  { "title": "ZK Version", "type": "text", "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 }, "content": "$version" },
  {
   "title": "Pakages Sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_packets_sent{instance=~\"$instance\",zk_host=~\"$name\"}",
     "legendFormat": "{{zk_host}}"
    }
   ]
  },
  {
   "title": "Pakages Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_packets_received{instance=~\"$instance\", zk_host=~\"$name\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(zk_num_alive_connections{instance=~\"$instance\", zk_host=~\"$name\"}[5m])",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_open_file_descriptor_count{instance=~\"$instance\", zk_host=~\"$name\"}",
     "legendFormat": "{{zk_host}}-open"
    },
    {
     "expr": "zk_max_file_descriptor_count{instance=~\"$instance\", zk_host=~\"$name\"}",
     "legendFormat": "{{zk_host}}-max"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_avg_latency{instance=~\"$instance\", zk_host=~\"$name\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Min Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_min_latency{instance=~\"$instance\", zk_host=~\"$name\"}",
     "legendFormat": "{{zk_host}}"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_max_latency{instance=~\"$instance\", zk_host=~\"$name\"}",
     "legendFormat": "{{zk_host}}"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_outstanding_requests{instance=~\"$instance\",zk_host=~\"$name\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Approx Data Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "zk_approximate_data_size{instance=~\"$instance\", zk_host=~\"$name\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  }
 ]
}